### ISSUE TITLE
Publication approval request for Web Browsing policy content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#10]
Copy of email sent.
[MOJ Digital Mail - Final review request for Web Browsing policy content.pdf](https://github.com/ministryofjustice/itpolicycontent/files/1531277/MOJ.Digital.Mail.-.Final.review.request.for.Web.Browsing.policy.content.pdf)

**Comment by warmanaMOJ** [comment]
Reply:

Hi Adrian,
 
The site itself is great and I would like to go ahead with publication as it improves the process for the user.
 
However, the new rule set still applies and I am no further forward in knowing when the implementation of Forcepoint is going ahead. Could you amend the page and leave the old rule set/categories in temporarily?  
 
Regards
 
Jennifer

**Comment by warmanaMOJ** [comment]
Hi,

No problem.

The revised main page (modified to exclude mention of Forcepoint) is previewable here: https://github.com/ministryofjustice/itpolicycontent/blob/webbrowsing/content/confluence/web-browsing.md
... and the link to the (old) list of policy rules is here: https://github.com/ministryofjustice/itpolicycontent/blob/webbrowsing/content/confluence/web-browsing-security-policy-profiles.md

If these changes are OK, I'll submit to Jon for formal approval to publish.

Many thanks,

Adrian

**Comment by warmanaMOJ** [comment]
Copy of email: 
[MOJ Digital Mail - Update to Web Browsing content.pdf](https://github.com/ministryofjustice/itpolicycontent/files/1539336/MOJ.Digital.Mail.-.Update.to.Web.Browsing.content.pdf)

**Comment by warmanaMOJ** [comment]
Reply:

Adrian,
 
It looks fine to me.
 
Regards
 
Jennifer

**Comment by warmanaMOJ** [comment]
Requesting approval to publish.

**Comment by warmanaMOJ** [comment]
The current (live) content is available here (spread across three tabs): https://intranet.justice.gov.uk/guidance/security/it-computer-security/web-browsing/

The proposed new content is available for preview, here:
https://ministryofjustice.github.io/itpolicycontent/content/confluence/web-browsing.html
https://github.com/ministryofjustice/itpolicycontent/blob/master/content/confluence/web-browsing-security-policy-profiles.md

The newer policy list is awaiting Forcepoint rollout. Meantime, Jennifer requested that we simply make the current policy list available.

**Comment by cybersquirrel** [comment]
- "Internet policy group and blocked URL categories are listed" - I think I know what this is saying, but it took me a moment. Is there a clearer phrasing?
- "What to do if a website is blocked" - it isn't obvious to me if we are asking everyone who experiences a blocked website to follow this process, or only if they think it's been blocked in error.
- "URL of the website visited" - is 'URL' a sufficiently widely understood term? Address of the website, maybe?

Other than these minor points, very happy to approve.

**Comment by warmanaMOJ** [comment]
Updated based on feedback.

As before, the current (live) content is available here (spread across three tabs): https://intranet.justice.gov.uk/guidance/security/it-computer-security/web-browsing/

The revised new content is available for preview, here:
https://ministryofjustice.github.io/itpolicycontent/content/confluence/web-browsing.html
https://github.com/ministryofjustice/itpolicycontent/blob/master/content/confluence/web-browsing-security-policy-profiles.md

**Comment by cybersquirrel** [comment]
Happy to approve!
