### ISSUE TITLE
Approval to Publish: System backup

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#23]
Hi Jon,

The System backup material is ready for publishing. All feedback and review comments have been addressed.

You can preview the final versions here:

- [https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-policy.html](https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-policy.html)
- [https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-standard.html](https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-standard.html)
- [https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-guidance.html](https://ministryofjustice.github.io/itpolicycontent/content/confluence/enterprise/system-backup-guidance.html)

Please may I request approval to publish?

Many thanks,

Adrian

**Comment by cybersquirrel** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you.
