### ISSUE TITLE
Approval to publish: Taking IT Equipment Abroad

### ISSUE THREAD

**Issue by tomdMOJ** [ministryofjustice/itpolicycontent#27]
Hi Jon,

Taking IT Equipment Abroad policy is ready for publishing, so I'm asking for your approval. It was worked on initially by Alana, then Jennifer took it over.

The following link shows the document:

https://ministryofjustice.github.io/itpolicycontent/content/taking-it-equipment-abroad.html

Thanks,

Tom

**Comment by cybersquirrel** [comment]
One comment:

> and to activate the remote wipe function

I thought (and hope!) that this capability is enabled on all of our devices already. Could we check this please and remove if unnecessary.

Other than this - approved!

Jon.
