### ISSUE TITLE
Approval to publish: Taking IT Equipment Abroad Guidance

### ISSUE THREAD

**Issue by tomdMOJ** [ministryofjustice/itpolicycontent#28]
Hi Jon,

This is the complementary guidance document to the policy. Again, it was worked on initially by Ahana before Jennifer and Dave gave final comments. Here is the link:

https://ministryofjustice.github.io/itpolicycontent/content/taking-it-equipment-abroad-guidance.html

Thanks,

Tom

**Comment by cybersquirrel** [comment]
> make sure you use the phone’s password or pin

PIN should be capitalised

Why is there are different route for reporting lost/stolen/compromised devices depending on whether it's a phone or a 'device'? That seems confusing to me.

Where does one get the tamper proof envelopes from?
