### ISSUE TITLE
Simplify the web browsing policy even more

### ISSUE THREAD

**Issue by cybersquirrel** [ministryofjustice/itpolicycontent#30]
Further to a conversation with some consumers of the web browsing policy, I think that (https://github.com/ministryofjustice/itpolicycontent/blob/master/content/confluence/web-browsing-security-policy-profiles-new.md) could be slimmed down further, to simply list out the 'blocked' categories for each type of user, thus reinforcing the idea that everything else is allowed by default.

**Comment by warmanaMOJ** [comment]
@cybersquirrel I've created new drafts of the policy profile docs, as suggested.

[This](https://github.com/ministryofjustice/itpolicycontent/blob/issue00030/content/confluence/web-browsing-security-policy-profiles.md) is the revised draft of the current (published) version.

[This](https://github.com/ministryofjustice/itpolicycontent/blob/issue00030/content/confluence/web-browsing-security-policy-profiles-new.md) is the revised draft of the new policy profiles, which will be published when I get confirmation that they are in place.

**Comment by cybersquirrel** [comment]
That looks a lot better - really happy with the new approach!

I think we should add a note to the 'legacy' (current) policy to say that this is for the legacy estate, and that a new policy is imminent (to avoid the copy+paste issue).
