### ISSUE TITLE
Add example of unacceptable use

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#38]
... to prevent use of personal accounts or email addresses when performing work tasks.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Please may I request approval to publish the updated [Acceptable Use](https://github.com/ministryofjustice/itpolicycontent/blob/issue0038/content/security/acceptable-use.md) content. It has been updated by adding an example of unacceptable use to **avoid**:
"using a personal account or personal email address for work tasks"

**Comment by cybersquirrel** [comment]
Approved! 👍

**Comment by warmanaMOJ** [comment]
Thank you.
