### ISSUE TITLE
Clarify lost laptop guidance for HMCTS

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#41]

**Comment by warmanaMOJ** [comment]
@tomdMOJ May I request your thoughts/feedback, please?

I've updated the [draft of the lost hardware guide](https://github.com/ministryofjustice/itpolicycontent/blob/issue0041/content/security/lost-laptophardware.md), to take account of some feedback to an ipc email (April 19th).

The current draft is everything up to the 'Legacy content' heading. Everything after the 'Legacy content' heading is leftover material from the current published version; I left it in for now, in case there's anything to carry over.

**Comment by warmanaMOJ** [comment]
<nudge> @tomdMOJ

**Comment by warmanaMOJ** [comment]
@cybersquirrel Please may I request a review on the revised/updated guidance for lost hardware (draft [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0041/content/security/lost-laptophardware.md) ).

Thank you.

**Comment by cybersquirrel** [comment]
Looks good to me

**Comment by warmanaMOJ** [comment]
@cybersquirrel Thank you. Please may I request approval to publish?

**Comment by cybersquirrel** [comment]
You may. Approved! :)

**Comment by warmanaMOJ** [comment]
Thank you. Published.
