### ISSUE TITLE
Clarify actions when a Line Manager is asked to approve a request, as part of a policy statement.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#43]

**Comment by warmanaMOJ** [comment]
@tomdMOJ Please, would you cast your eye over [this draft](https://github.com/ministryofjustice/itpolicycontent/blob/issue0043/content/security/line-manager-approval.md)? Many thanks.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Please may I request approval to publish [this guidance](https://github.com/ministryofjustice/itpolicycontent/blob/issue0043/content/security/line-manager-approval.md).

**Comment by cybersquirrel** [comment]
Hi @warmanaMOJ - as a LM I'm not sure quite what's being asked of me on point (3). Also a spurious colon on point (9). Other than this looks good.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Thank you - I have clarified step 3. Its meant to make sure that AUP is always taken into account. The superfluous colon in step 9 is a side effect of the mechanism we use to avoid including specific contact details or personal information within the GitHub repository. When the content is published, it will correctly pick up the contact details from the Intranet.

Please, may I request approval to publish?

**Comment by warmanaMOJ** [comment]
@cybersquirrel {nudge}

**Comment by cybersquirrel** [comment]
Approved!

**Comment by warmanaMOJ** [comment]
Published.
