### ISSUE TITLE
Clarify customisation of equipment as part of AUP.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#44]

**Comment by warmanaMOJ** [comment]
Added paragraph on 'Personalisation of equipment' to the end of the AUP.

@cybersquirrel Please may I request approval to publish?

**Comment by warmanaMOJ** [comment]
@cybersquirrel {nudge} The new paragraph is visible at the end of the draft document, [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0044/content/security/acceptable-use.md).

**Comment by warmanaMOJ** [comment]
@cybersquirrel We just had a query regarding this topic; please may I gently {nudge} again?

**Comment by cybersquirrel** [comment]
Nudge duly noted. Am checking about the desktop picture as I'm not convinced this is correct.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Updated as discussed, [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0044/content/security/acceptable-use.md).

**Comment by cybersquirrel** [comment]
Approved.

**Comment by warmanaMOJ** [comment]
Thank you, published.
