### ISSUE TITLE
Approval to publish: Interim OIT guidance.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#45]

**Comment by warmanaMOJ** [comment]
I have created an interim guide for use of Open Internet Tools, [here](https://github.com/ministryofjustice/itpolicycontent/blob/openinternettools/content/security/guidance-for-using-open-internet-tools.md)

@cybersquirrel Please may I request approval to publish?

**Comment by warmanaMOJ** [comment]
I have now had feedback from Jack C. and incorporated his points. I have also modified the confusing terminology you mentioned above.

The revised draft is visible [here](https://github.com/ministryofjustice/itpolicycontent/blob/openinternettools/content/security/guidance-for-using-open-internet-tools.md).

@cybersquirrel Please may I request approval to publish?

**Comment by cybersquirrel** [comment]
Approved! A good piece of work, albeit one that's going to be a work in progress for many moons to come!

**Comment by warmanaMOJ** [comment]
Thank you. Published.
