### ISSUE TITLE
Convert IT Security Guide from PDF to MD.

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#46]

**Comment by warmanaMOJ** [comment]
@cybersquirrel In order to publish a revised Leaver's Checklist for Managers, it makes sense to convert the current IT Security Guide PDF (which refers to the checklist) to an Intranet page equivalent. This will facilitate later work. It is also necessary to modify the IT Security Framework landing page to refer to the IT Security Guide Intranet page rather than the PDF.

Please may I request approval to publish the following changes:
1. A new Leaver's Checklist for Managers, as requested by Security Analyst Vinod P.
2. A Intranet page replacement (preview [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0046/content/security/framework/it-security-guidelines.md) ) for the current [IT Security Guide PDF](https://intranet.justice.gov.uk/documents/2015/04/it-security-guidelines.pdf); apart from the format change, the only difference to content is to refer to the new Leaver's Checklist for Managers.
3. A modification to the [IT Security Framework](https://intranet.justice.gov.uk/guidance/security/it-computer-security/ict-security-policy-framework/) landing page, to refer to the new IT Security Guide Intranet page rather than the PDF (preview [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0046/content/security/framework/ict-security-policy-framework.md) ).
4. A 'stub' PDF (preview [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0046/content/security/framework/it-security-guidelines.pdf) ) to replace the current IT Security Guide PDF.

**Comment by cybersquirrel** [comment]
Hi @warmanaMOJ 

I don't see a link to item (1) the new checklist?
2, 3, and 4 are fine.

**Comment by warmanaMOJ** [comment]
@cybersquirrel Oops, apologies, the link is in the IT Security Guide Intranet page draft, but this is it: [https://intranet.justice.gov.uk/documents/2018/05/leavers-checklist-for-managers-3.docx](https://intranet.justice.gov.uk/documents/2018/05/leavers-checklist-for-managers-3.docx)

**Comment by cybersquirrel** [comment]
Ok, only thing that seems slightly unexpected is the bold text in the 'Tell IT' section, which feels ever so slightly in the wrong place. Not sure where else to put it though! Either way, happy to approve.

**Comment by warmanaMOJ** [comment]
@cybersquirrel The Leaver's checklist document is the one supplied as-is by HR, so I haven't touched it at all.

Anyway, all published now. Thank you.
