### ISSUE TITLE
Copy of content publication approval request

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#5]
Copy of the email sent, requesting approval to publish some content on the Intranet.

Email used, as an interested party does not have a GitHub account.

[MOJ Digital Mail - Content publication approval request.pdf](https://github.com/ministryofjustice/itpolicycontent/files/1449688/MOJ.Digital.Mail.-.Content.publication.approval.request.pdf)

**Comment by cybersquirrel** [comment]
Email sent regarding concerns over (extreme) legacy content, and publishing this onto intranet.

**Comment by warmanaMOJ** [comment]
Closing, as superseded by fresh approval request.
