### ISSUE TITLE
Approval - Government Classification Scheme

### ISSUE THREAD

**Issue by tomdMOJ** [ministryofjustice/itpolicycontent#55]
Hi Jon,

Our legacy Government Classification Scheme guide was short, only showing a link to the detailed guide at the Cabinet Office. I've updated the link and reference, and added a bit of background information to freshen it up. 

Let me know if you're happy for me to publish it. The link to the draft is:

https://github.com/ministryofjustice/itpolicycontent/blob/master/content/security/government-classification-scheme.md

Thanks,

Tom

**Comment by cybersquirrel** [comment]
Only comment is that the first word should probably be "These" rather than "This"? Other than this, approved!

**Comment by tomdMOJ** [comment]
Agree, and will make the change, and publish!

Thanks for your prompt reply on this one Jon.

**Comment by warmanaMOJ** [comment]
Closing as published.
