### ISSUE TITLE
Publish new webmail access rules, in parallel with old rules

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#60]
People who have been migrated to O365 are now using the new webmail access rules. Others - and those not migrated - are still using the old rules.

So, need to have both sets published in parallel.

**Comment by warmanaMOJ** [comment]
@cybersquirrel 
The following content has been published/updated:

- [What's New and Changes](https://intranet.justice.gov.uk/guidance/security/it-computer-security/00-whatsnew/)
- [Web browsing security](https://intranet.justice.gov.uk/guidance/security/it-computer-security/web-browsing/)
- [Web browsing security policy profiles](https://intranet.justice.gov.uk/guidance/security/it-computer-security/web-browsing-security-policy-profiles/)
- [Web browsing security policy profiles (New)](https://intranet.justice.gov.uk/guidance/security/it-computer-security/web-browsing-security-policy-profiles-new/)

Please may I request retrospective approval for the publication?

**Comment by cybersquirrel** [comment]
Approved

**Comment by warmanaMOJ** [comment]
Thank you.
