### ISSUE TITLE
Clarify that password guidance is password specific

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#64]
The new password guidance applies to password management, not account management. Existing account management practices should be unaffected.

**Comment by warmanaMOJ** [comment]
@cybersquirrel 

I have added a clarification paragraph ( [here](https://github.com/ministryofjustice/itpolicycontent/blob/issue0064/content/security/framework/password-standard.md#account-management) ).

Please may I request approval to publish this update? Thank you.

**Comment by cybersquirrel** [comment]
Absolutely fine. Approved!

**Comment by warmanaMOJ** [comment]
Thank you very much.
