### ISSUE TITLE
Request to approve publication of migrated Confluence content

### ISSUE THREAD

**Issue by warmanaMOJ** [ministryofjustice/itpolicycontent#8]
[MOJ Digital Mail - Request to approve publication of migrated Confluence content.pdf](https://github.com/ministryofjustice/itpolicycontent/files/1513426/MOJ.Digital.Mail.-.Request.to.approve.publication.of.migrated.Confluence.content.pdf)

**Comment by cybersquirrel** [comment]
Approved - happy with this approach given the way the content is being migrated and marked.
